var quotes = [

	'Two ethicists working with Australian universities argue in the latest online edition of the Journal of Medical Ethics that if abortion of a fetus is allowable, so to should be the termination of a newborn.',
	'The intense controversy that this question engenders is remarkable. On the left, critics of assertive American foreign, military, and economic policies depict these policies as aggressively immoral by branding them “imperial.” On the right, advocates for an even more forceful application of American “hard power,” such as Niall Ferguson and the other members of his self-described “neo-imperialist gang,” argue that the United States should use its immense wealth and military might to impose order and stability on an increasingly chaotic world.',
	'<i>And I say to mankind, Be not curious about God, / For I who am curious about each am not curious about God, /  (No array of terms can say how much I am at peace about God and about death.) /  I hear and behold God in every object, yet understand God not in the least.</i> (Walt Whitman, <i> Leaves of Grass </i>). Question -- Is Whitmans peace about God genuine? Should we be curious about God or be at peace seeing and beholding God in every object but not understanding Him in the least?'
	'Where is my dewelling place? Where I can never stand. / Where is my final goal, toward which I should ascend? / It is beyond all place. What should my quest then be? / I must, transcending God, into the desert flee. (Angelus Silesius, Cherubinic Wanderer, "One Must Go Beyond God") Question: Is it possible to go "beyond God"? What does this phrase mean? Is it advisable to "transcend God"? What is the "desert"?'
	'Diogenes Laertius cites life, health, pleasure, beauty, strength, wealth, good reputation, and noble birth as examples of preferables, and death, disease, pain, ugliness, poverty, ad reputation, and low birth, as examples of non-preferables.” (Nicholas Wolterstorff, *Justice: Rights and Wrongs*, (Princeton: 2008), 162). Question: Are the preferables Laertius mentions actually  necessary or really just preferable? Are his "non-preferables" horrifying tragedies or merely non-preferrable?'
	'If Judaism is a religion, then Christianity is a religion. If Christianity is not a religion, then Judaism is not a religion. Question: Is Christianity a religion?'
	'Adams also excoriated the French speculators not only for their infatuation with human perfectibility, but also for their love of equality. Adams insisted that, far from all men being substantially equal, there actually is a natural aristocracy of men, formed from the benefactors of the unavoidable inequality of humankind. Like Burke, Adams held to every man having equal rights to his own and equal standing before God. Beyond that, though, men are unequal in their powers and faculties, influence in society, property and advantages, piety and iniquity, and nearly every other attribute.” (Russel Kirk, “The Conservative Mind”). Question: Are human beings "equal"? If so, in what respect? If not, then is equality a moral ideal or not?'
	]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}